application: thinkimj
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /static/
  static_dir: static/

- url: /(.*\.(php|html))
  script: \1

- url: /.*
  script: myhome.html